Create grit basis for mobile version
serg-rsv/team-project-01 pull request #2
Opened 2022-01-27 17:43 UTC by Nikolay-Tymoshchuk

2022-01-27 18:49 UTC, serg-rsv requested changes
*перемести стили галереи в components\gallery
*перед следующим пулом обнови ветку main
*нужно центрировать галерею по центру секции

2022-01-27 18:49 UTC, serg-rsv commented on src/sass/_gallery.scss
> +  display: grid;
попробуй центрировать марджинами авто слева и справа

2022-01-27 20:36 UTC, Nikolay-Tymoshchuk commented on src/sass/_gallery.scss
> +  display: grid;
Да я не выравнивал там ничего, я то и пул реквест не хотел делать пока, но на видео демонстрации сделал. Я так, чисто баловался, ну сейчас уже сделал выравнивание и переместил куда надо стили галереи

2022-01-28 05:34 UTC, serg-rsv approved these changes, later dismissed

2022-01-28 05:40 UTC, serg-rsv commented on src/partials/gallery.html
> +                    src="/images/kulfi40@1x.jpg" alt="Блюдо индийской кухни Кульфи" /></li>
язык сайта у нас EN, alt соответсвенно будет "Kulfi Indian cuisine dish"

2022-01-29 11:38 UTC, serg-rsv approved these changes

2022-01-29 11:38 UTC, merged